Repository jong1uk/popcorn-buddy, pull requests merged in 2024-03, with the labels that each got.

#24 test
  page/login_sign_up/style.css
Labels: enhancement

#26 test
  page/join-room/4-5page.html
Labels: bug

#30 hi
  .DS_Store
  page/.DS_Store
  page/03_main/multislider.html
Labels: duplicate

#34 test
  page/02_login_sign_up/index.html
Labels: duplicate
